### ISSUE TITLE
GHC 7.10.1 Missing compiler flag.

### ISSUE THREAD

**Issue by Posnet** [unisonweb/platform#6]
Arch Linux 64-bit  Kernel 3.19.3-3-ARCH
The Glorious Glasgow Haskell Compilation System, version 7.10.1
```
[ 9 of 21] Compiling Unison.ABT       ( src/Unison/ABT.hs, dist/dist-sandbox-49d2760b/build/Unison/ABT.o )
src/Unison/ABT.hs:224:13:
    Non type-variable argument
      in the constraint: Integral (Data.Bytes.Signed.Unsigned n)
    (Use FlexibleContexts to permit this)
    When checking that ‘hashInt’ has the inferred type
```

Required adding the following before it would compile:
```
index 6b02f04..921c611 100644
--- a/node/unison.cabal
+++ b/node/unison.cabal
@@ -90,7 +90,7 @@ library
     transformers-compat       ,
     vector                    >= 0.10.11.0
 
-  ghc-options: -Wall -fno-warn-name-shadowing -threaded -rtsopts -with-rtsopts=-N
+  ghc-options: -Wall -fno-warn-name-shadowing -threaded -rtsopts -with-rtsopts=-N -XFlexibleContexts
```

**Comment by pchiusano** [comment]
Aha. Could we just add a type annotation there - specializing to int there
is perfectly fine. I'd rather that than flexible contexts. Or rather, I
want to use flexible contexts intentionally, not because something is more
polymorphic than intended.

I'm going to upgrade to ghc 7.10 early next week so I can fix this stuff
first hand.
